remote:
  host: "127.0.0.1"
  port: 23000
sim:
  scene_path: "/messaging/movementViaRemoteApitest.ttt"
  switch_period_s: 10.0
  delta_per_step: 0.02
  delta_per_step2: 0.002
  grid_size: 0.25
  scaling_factor: 40.0
run:
  max_steps: 50     # 先别追求“永动”，项目里建议可控
  print_every: 1
objects:
  - name: "UR5_1"
    path: "/UR5_1"
    type: "robot"
  - name: "UR5_2"
    path: "/UR5_2"
    type: "robot"

  - name: "Block_0"
    path: "/Block_0"
    type: "block"
    
  - name: "Block_1"
    path: "/Block_1"
    type: "block"
  - name: "Block_2"
    path: "/Block_2"
    type: "block"
  - name: "Block_3"
    path: "/Block_3"
    type: "block"
  - name: "Block_4"
    path: "/Block_4"
    type: "block"  
  - name: "Block_5"
    path: "/Block_5"
    type: "block"
  - name: "Block_6"
    path: "/Block_6"
    type: "block"
  - name: "Block_7"
    path: "/Block_7"
    type: "block"
  - name: "Block_8"
    path: "/Block_8"
    type: "block"
  - name: "Block_9"
    path: "/Block_9"
    type: "block"
  - name: "Block_10"
    path: "/Block_10"
    type: "block"
  - name: "Block_11"
    path: "/Block_11"
    type: "block"  
  - name: "Block_12"
    path: "/Block_12"
    type: "block"
  - name: "Block_13"
    path: "/Block_13"
    type: "block"
  - name: "Block_14"
    path: "/Block_14"
    type: "block"
  - name: "Block_15"
    path: "/Block_15"
    type: "block"  
  - name: "Block_16"
    path: "/Block_16"
    type: "block"
  - name: "Block_17"
    path: "/Block_17"
    type: "block"
  - name: "Block_18"
    path: "/Block_18"
    type: "block"

  - name: "Cuboid_1"
    path: "/Cuboid_1"
    type: "cuboid"
  - name: "Cuboid_2"
    path: "/Cuboid_2"
    type: "cuboid"
  - name: "Cuboid_3"
    path: "/Cuboid_3"
    type: "cuboid"
  - name: "Cuboid_4"
    path: "/Cuboid_4"
    type: "cuboid"
  - name: "Cuboid_5"
    path: "/Cuboid_5"
    type: "cuboid"
  - name: "Cuboid_6"
    path: "/Cuboid_6"
    type: "cuboid"

